JongsikLEE01/MSA5_MainProject

- daeut/src/main/resources/static/css/layoutCss.css
- daeut/src/main/resources/templates/error/404.html
- daeut/src/main/resources/templates/fragment/footer.html
- daeut/src/main/resources/templates/fragment/header.html
- daeut/src/main/resources/templates/fragment/link.html
> Jslee 헤더푸터수정

- daeut/src/main/resources/static/css/index.css
- daeut/src/main/resources/static/js/reservation/payment.js
- daeut/src/main/resources/static/js/reservation/reservation.js
- daeut/src/main/resources/templates/index.html
- daeut/src/main/resources/templates/reservation/chat.html
- daeut/src/main/resources/templates/reservation/payment.html
- daeut/src/main/resources/templates/reservation/paymentDone.html
> Jslee~~~ 24일 할거 끝~

- daeut/src/main/resources/templates/admin/adminPartnerRead.html
- daeut/src/main/resources/templates/reservation/reservationRead.html
- daeut/src/main/resources/templates/user/userMypage.html
- daeut/src/main/resources/templates/user/userPartner.html
> 05.28 Jslee 유저 파트너 끝

- daeut/src/main/resources/com/daeut/daeut/reservation/mapper/FileMapper.xml
- daeut/src/main/resources/com/daeut/daeut/reservation/mapper/ReservationMapper.xml
Jslee 컬럼명 변경, 수정 조회 html 수정 필요
> Jslee 컬럼명 변경, 수정 조회 html 수정 필요 

- daeut/SQL/DDL.sql
- daeut/src/main/java/com/daeut/daeut/reservation/controller/FileController.java
- daeut/src/main/java/com/daeut/daeut/reservation/controller/ReservationController.java
- daeut/src/main/java/com/daeut/daeut/reservation/dto/Files.java
- daeut/src/main/java/com/daeut/daeut/reservation/dto/Services.java
- daeut/src/main/java/com/daeut/daeut/reservation/mapper/ReservationMapper.java
- daeut/src/main/java/com/daeut/daeut/reservation/service/ReservationService.java
- daeut/src/main/java/com/daeut/daeut/reservation/service/ReservationServiceImpl.java
- daeut/src/main/resources/com/daeut/daeut/reservation/mapper/FileMapper.xml
- daeut/src/main/resources/com/daeut/daeut/reservation/mapper/ReservationMapper.xml
- daeut/src/main/resources/static/css/reservation/reservation.css
- daeut/src/main/resources/static/css/style.css
- daeut/src/main/resources/static/js/reservation/reservation.js
- daeut/src/main/resources/templates/reservation/payment.html
- daeut/src/main/resources/templates/reservation/reservation.html
- daeut/src/main/resources/templates/reservation/reservationInsert.html
- daeut/src/main/resources/templates/reservation/reservationRead.html
- daeut/src/main/resources/templates/reservation/reservationUpdate.html
> 언제쯤 나는 집에 갈 수 있을까요?

- daeut/src/main/java/com/daeut/daeut/auth/controller/UserController.java
- daeut/src/main/java/com/daeut/daeut/auth/service/UserServiceImpl.java
- daeut/src/main/resources/templates/user/userCart.html
- daeut/src/main/resources/templates/user/userMypageUpdate.html
> Jslee 장바구니경로 및 html

- daeut/src/main/resources/application.properties
- daeut/src/main/resources/com/daeut/daeut/main/mapper/FileMapper.xml
FileMapper 경로 main 으로 변경, type-aliases 추가
> FileMapper 경로 main 으로 변경, type-aliases 추가

- .vscode/settings.json
- daeut/src/main/java/com/daeut/daeut/auth/controller/UserController.java
- daeut/src/main/java/com/daeut/daeut/main/controller/FileController.java
- daeut/src/main/java/com/daeut/daeut/main/controller/HomeController.java
- daeut/src/main/java/com/daeut/daeut/main/service/FileServiceImpl.java
- daeut/src/main/java/com/daeut/daeut/reservation/controller/CartController.java
- daeut/src/main/java/com/daeut/daeut/reservation/mapper/CartMapper.java
- daeut/src/main/java/com/daeut/daeut/reservation/service/CartService.java
- daeut/src/main/java/com/daeut/daeut/reservation/service/CartServiceImpl.java
- daeut/src/main/java/com/daeut/daeut/reservation/service/ReservationService.java
- daeut/src/main/java/com/daeut/daeut/reservation/service/ReservationServiceImpl.java
- daeut/src/main/resources/com/daeut/daeut/reservation/mapper/CartMapper.xml
- daeut/src/main/resources/static/js/reservation/reservation.js
- daeut/src/main/resources/static/js/user/script.js
- daeut/src/main/resources/templates/layout/payment_layout.html
- daeut/src/main/resources/templates/layout/user_layout.html
- daeut/src/main/resources/templates/reservation/reservation.html
- daeut/src/main/resources/templates/reservation/reservationRead.html
- daeut/src/main/resources/templates/user/userCart.html
> Jslee 장바구니끝

- daeut/src/main/java/com/daeut/daeut/reservation/controller/OrdersController.java
- daeut/src/main/java/com/daeut/daeut/reservation/service/PaymentServiceImpl.java
- daeut/src/main/resources/com/daeut/daeut/auth/mapper/UserMapper.xml
- daeut/src/main/resources/com/daeut/daeut/reservation/mapper/OrdersMapper.xml
- daeut/src/main/resources/templates/reservation/reservationRead.html
서버 작동확인, payment, order은 테스트 X
> 서버 작동확인, payment, order은 테스트 X

- daeut/src/main/java/com/daeut/daeut/reservation/controller/OrderController.java
- daeut/src/main/java/com/daeut/daeut/reservation/controller/ReservationController.java
- daeut/src/main/resources/com/daeut/daeut/reservation/mapper/PaymentMapper.xml
- daeut/src/main/resources/static/js/reservation/payment.js
- daeut/src/main/resources/templates/reservation/payment.html
- daeut/src/main/resources/templates/reservation/paymentDone.html
- daeut/src/main/resources/templates/reservation/paymentFalse.html
> 24.06.03 결제 끝 / 환불 X

- daeut/src/main/java/com/daeut/daeut/auth/controller/UserController.java
- daeut/src/main/java/com/daeut/daeut/auth/mapper/UserMapper.java
- daeut/src/main/java/com/daeut/daeut/auth/service/UserService.java
- daeut/src/main/java/com/daeut/daeut/auth/service/UserServiceImpl.java
- daeut/src/main/resources/com/daeut/daeut/auth/mapper/UserMapper.xml
public Users findUserById(int userNo) throws Exception; 추가
> public Users findUserById(int userNo) throws Exception; 추가

- daeut/src/main/java/com/daeut/daeut/auth/controller/UserController.java
- daeut/src/main/java/com/daeut/daeut/config/WebSocketConfig.java
- daeut/src/main/java/com/daeut/daeut/reservation/controller/ChatController.java
- daeut/src/main/java/com/daeut/daeut/reservation/service/ChatRoomServiceImpl.java
- daeut/src/main/resources/templates/reservation/chat.html
> 삭젠ㄴㄴㄴㄴㄴㄴㄴㄴㄴㄴㄴㄴㄴㄴㄴㄴㄴㄴㄴㄴㄴㄴㄴㄴ

- daeut/SQL/DDL.sql
- daeut/src/main/java/com/daeut/daeut/auth/controller/UserController.java
- daeut/src/main/java/com/daeut/daeut/reservation/controller/CartController.java
- daeut/src/main/java/com/daeut/daeut/reservation/controller/OrderController.java
- daeut/src/main/java/com/daeut/daeut/reservation/controller/ReservationController.java
- daeut/src/main/java/com/daeut/daeut/reservation/dto/Payments.java
- daeut/src/main/resources/com/daeut/daeut/reservation/mapper/PaymentMapper.xml
- daeut/src/main/resources/static/js/reservation/payment.js
- daeut/src/main/resources/templates/admin/adminReservation.html
- daeut/src/main/resources/templates/admin/adminReservationRead.html
- daeut/src/main/resources/templates/reservation/paymentDone.html
- daeut/src/main/resources/templates/user/userCart.html
- deautERD.vuerd.json
> 장바구니, 예약글, 주문 수정 끝 수정 XXXXXXXXXXXXXXXXX

- daeut/SQL/TES.sql
- daeut/TODO.md
- daeut/src/main/java/com/daeut/daeut/reservation/controller/OrderController.java
- daeut/src/main/java/com/daeut/daeut/reservation/mapper/CartMapper.java
- daeut/src/main/java/com/daeut/daeut/reservation/service/CartService.java
- daeut/src/main/java/com/daeut/daeut/reservation/service/CartServiceImpl.java
- daeut/src/main/resources/com/daeut/daeut/reservation/mapper/CartMapper.xml
> 06/08 11:15 Todo.md 생성

- daeut/SQL/DDL.sql
- daeut/TODO.md
- daeut/src/main/java/com/daeut/daeut/main/dto/ServicePage.java
- daeut/src/main/java/com/daeut/daeut/reservation/controller/CartController.java
- daeut/src/main/java/com/daeut/daeut/reservation/controller/OrderController.java
- daeut/src/main/java/com/daeut/daeut/reservation/controller/ReservationController.java
- daeut/src/main/java/com/daeut/daeut/reservation/dto/PaymentStatus.java
- daeut/src/main/java/com/daeut/daeut/reservation/mapper/ReservationMapper.java
- daeut/src/main/java/com/daeut/daeut/reservation/service/CartService.java
- daeut/src/main/java/com/daeut/daeut/reservation/service/CartServiceImpl.java
- daeut/src/main/java/com/daeut/daeut/reservation/service/ReservationService.java
- daeut/src/main/java/com/daeut/daeut/reservation/service/ReservationServiceImpl.java
- daeut/src/main/resources/application.properties
- daeut/src/main/resources/com/daeut/daeut/reservation/mapper/OrderMapper.xml
- daeut/src/main/resources/com/daeut/daeut/reservation/mapper/ReservationMapper.xml
- daeut/src/main/resources/templates/reservation/payment.html
- daeut/src/main/resources/templates/reservation/reservation.html
- daeut/src/main/resources/templates/reservation/reservationRead.html
- deautERD.vuerd.json
> Jslee 0608  작업

- daeut/TODO.md
- daeut/src/main/java/com/daeut/daeut/reservation/controller/OrderController.java
- daeut/src/main/java/com/daeut/daeut/reservation/dto/Cancel.java
- daeut/src/main/resources/com/daeut/daeut/reservation/mapper/CancelMapper.xml
- daeut/src/main/resources/templates/user/cancelDone.html
- daeut/src/main/resources/templates/user/userReservation.html
- daeut/src/main/resources/templates/user/userResevationCancel.html
> 어드민 환불 승인부터 해야함

- daeut/src/main/java/com/daeut/daeut/auth/dto/Review.java
- daeut/src/main/java/com/daeut/daeut/auth/mapper/ReviewMapper.java
- daeut/src/main/java/com/daeut/daeut/auth/service/ReviewService.java
- daeut/src/main/java/com/daeut/daeut/auth/service/ReviewServiceImpl.java
- daeut/src/main/java/com/daeut/daeut/reservation/controller/ReservationController.java
- daeut/src/main/resources/com/daeut/daeut/auth/mapper/ReviewMapper.xml
- daeut/src/main/resources/templates/reservation/reservationRead.html
> Read에 리뷰가 안 떠

- daeut/src/main/java/com/daeut/daeut/reservation/controller/ReservationController.java
- daeut/src/main/java/com/daeut/daeut/reservation/mapper/ReservationMapper.java
- daeut/src/main/java/com/daeut/daeut/reservation/service/ReservationService.java
- daeut/src/main/java/com/daeut/daeut/reservation/service/ReservationServiceImpl.java
- daeut/src/main/resources/com/daeut/daeut/reservation/mapper/ReservationMapper.xml
- daeut/src/main/resources/templates/partner/partnerMypage.html
- daeut/src/main/resources/templates/partner/partnerMypageUpdate.html
- daeut/src/main/resources/templates/reservation/reservationRead.html
> Read 페이지 파트너 썸네일(엑박뜸)

- daeut/src/main/java/com/daeut/daeut/reservation/mapper/ReservationMapper.java
- daeut/src/main/resources/static/css/admin/admin.css
- daeut/src/main/resources/static/css/partner/partner.css
- daeut/src/main/resources/static/css/reservation/reservation.css
- daeut/src/main/resources/static/css/tip/tip.css
- daeut/src/main/resources/static/css/user/user.css
- daeut/src/main/resources/templates/reservation/reservation.html
- daeut/src/main/resources/templates/reservation/reservationRead.html
> 파트너 썸네일 & 페이지네이션css 수정

- daeut/src/main/java/com/daeut/daeut/auth/mapper/ReviewMapper.java
- daeut/src/main/java/com/daeut/daeut/auth/service/ReviewService.java
- daeut/src/main/java/com/daeut/daeut/auth/service/ReviewServiceImpl.java
- daeut/src/main/java/com/daeut/daeut/reservation/controller/ReservationController.java
- daeut/src/main/java/com/daeut/daeut/reservation/mapper/ReservationMapper.java
- daeut/src/main/java/com/daeut/daeut/reservation/service/ReservationService.java
- daeut/src/main/java/com/daeut/daeut/reservation/service/ReservationServiceImpl.java
- daeut/src/main/resources/com/daeut/daeut/auth/mapper/ReviewMapper.xml
- daeut/src/main/resources/com/daeut/daeut/reservation/mapper/ReservationMapper.xml
- daeut/src/main/resources/templates/reservation/reservationRead.html
> 리뷰 이미지 성공!!!

- daeut/src/main/java/com/daeut/daeut/reservation/controller/ReservationController.java
> 리뷰 이미지 띄우기

- daeut/SQL/회원샘플.sql
- daeut/src/main/resources/templates/partner/partnerMypage.html
- daeut/src/main/resources/templates/partner/partnerMypageUpdate.html
- daeut/src/main/resources/templates/reservation/reservationRead.html
> 파트너 페이지 오류 수정

- daeut/src/main/java/com/daeut/daeut/auth/mapper/ReviewMapper.java
- daeut/src/main/java/com/daeut/daeut/auth/service/LoginSuccessHandler.java
- daeut/src/main/java/com/daeut/daeut/auth/service/ReviewService.java
- daeut/src/main/java/com/daeut/daeut/auth/service/ReviewServiceImpl.java
- daeut/src/main/java/com/daeut/daeut/reservation/controller/ReservationController.java
- daeut/src/main/resources/com/daeut/daeut/auth/mapper/ReviewMapper.xml
- daeut/src/main/resources/templates/reservation/reservationRead.html
> 리뷰 삭제 완!!!
